# Generated by Django 4.2.24 on 2025-10-19 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='specialization',
            field=models.CharField(blank=True, choices=[('lifestyle', 'Lifestyle'), ('sports', 'Sports'), ('technology', 'Technology'), ('Culture', 'Culture'), ('news', 'News'), ('business', 'Business')], max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Specialization',
        ),
    ]
